apiVersion: v1
kind: Namespace
metadata:
  name: recruitment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitment-app
  namespace: recruitment
  labels:
    app: recruitment-app
spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: recruitment-app

  template:
    metadata:
      labels:
        app: recruitment-app
    spec:
      containers:
      - name: recruitment-app
        image: vignesh8386/recruitment-app:v1.1.0
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef: 
              name: config
              key: MONGO_URL
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: hr-app-config
              key: DB_NAME
