apiVersion: v1
kind: Service
metadata:
  name: recruitment-service
  namespace: recruitment
spec:
  selector:
    app: recruitment-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: NodePort
